CREATE TABLE campaigns (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  agency_id       UUID NOT NULL REFERENCES agencies(id),
  client_id       UUID NOT NULL REFERENCES clients(id),
  service_id      UUID REFERENCES services(id),
  name            TEXT NOT NULL,
  type            TEXT,
  status          TEXT DEFAULT 'planning',
  period_start    DATE,
  period_end      DATE,
  brief_raw       TEXT,
  objective       TEXT,
  outcome         TEXT,
  learnings       TEXT,
  drive_folder_id TEXT,
  notion_page_id  TEXT,
  extra           JSONB DEFAULT '{}',
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  updated_at      TIMESTAMPTZ DEFAULT NOW()
);
